### ISSUE TITLE
how to train my own model

### ISSUE THREAD

**Issue by hemanthkumar3111** [AhmetHamzaEmra/Intelegent_Lock#20]
i just want to know how i can train my own model on top of yours

**Comment by AhmetHamzaEmra** [comment]
Hi,

once you get a small dataset with both positive and negative samples, re-train the network for couple epochs. 
Basicaly go to `main_code.py` and change the following part. 
```(python)
# load weights into new model
model.load_weights("model/model.h5")
print("Loaded model from disk")

model.compile(optimizer=tf.train.AdamOptimizer(0.001),
              loss='categorical_crossentropy')

# dont train for long 
# make sure your get right dimentions 
model.fit(your_images, your_labels, epochs=3)

```

Since I dont upgraded keras to tf2 backend, I couldn't test this code. Let me know if it doesnt work, I can find something for you. 

Regards
