### ISSUE TITLE
retrain

### ISSUE THREAD

**Issue by raminrahimi6970** [AhmetHamzaEmra/Intelegent_Lock#25]
Hi thanks for your rep
I want to train with my datasets but I cant find finetuning script in your codes..
would you please to send me your finetuning script?
thanks you advanced for your reply

**Comment by AhmetHamzaEmra** [comment]
Hi,

once you get a small dataset with both positive and negative samples, re-train the network for couple epochs. 
Basicaly go to `main_code.py` and change the following part. 
```(python)
# load weights into new model
model.load_weights("model/model.h5")
print("Loaded model from disk")

model.compile(optimizer=tf.train.AdamOptimizer(0.001),
              loss='categorical_crossentropy')

# dont train for long 
# make sure your get right dimentions 
model.fit(your_images, your_labels, epochs=3)

```

Since I didn't upgrade keras to tf2 backend, I couldn't test this code. Let me know if it doesnt work, I can find something for you. 

Regards

**Comment by raminrahimi6970** [comment]
HI
thanks regards

**Comment by woreom** [comment]
Hi, I have a somewhat big dataset I wanted to retrain with your model since my own models aren't performing as well, should I have videos or can I finetune with images?
