### ISSUE TITLE
The trained model doesn't work well on phone recorded video

### ISSUE THREAD

**Issue by JellyJ98** [AhmetHamzaEmra/Intelegent_Lock#29]
When I tested this model by using laptop camera, everything works beautifully.
But when I upload a phone recorded video and let the model to predict is it a live person, the model actually return a very low accuracy (the model often return les than 5% prediction even though it is a live person).
Do you have any idea how to solve this? 
Maybe we can dive deeper, what's the dataset you used to train this liveness detection model?

**Comment by AhmetHamzaEmra** [comment]
Flask has some problem when it comes to sending image data to server and retrewing information. I had the same problem in the past and unfortunutely its not realy anything that we can fix with model. Only think that comes to my mind in chaning python to javascript and haningling it on the device instead of server. If you want to follow that way, I can try to help you but honestly not my strong suit.
